---

- hosts: all
  become: true
  tasks:

  - name: upate repository indexx
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install apache2 package
    apt:
      name: apache2
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install php support for apache
    apt:
      name: libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"


  - name: upate CentOS repository indexx
    dnf:
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: install apache2 package CentOS
    dnf:
      name: httpd
      state: latest
    when: ansible_distribution == "CentOS"

  - name: install php support for apache CentOS
    dnf:
      name: php
      state: latest
    when: ansible_distribution == "CentOS"

