---

- hosts: all
  become: true
  tasks:

  - name: Update repository index and install apache and PHP packages for Ubuntu
    package:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install apache and php for CentOS
    dnf:
      name:
        - httpd
        - php
      state: latest

